
const APP_VERSION="2.0.0";const store={single:{},multi:{}};let currentMeal=null,deferredPrompt=null;
const mealNames={pre:"לפני אימון",shake:"שייק אחרי אימון",b:"בוקר בעבודה",l:"צהריים בעבודה",d:"ערב בבית",s:"ערב שני"};
const mealEmoji={pre:"🏋️",shake:"🥤",b:"🍳",l:"🍚",d:"🥩",s:"🥛"};
const typeNames={protein:"חלבון",carb:"פחמימה",veg:"ירקות",sauce:"רטבים",oats:"שיבולת",choco:"שוקולית",milk:"חלב",scoop:"סקופים",flavor:"טעם",liquid:"נוזל",eggs:"ביצים",tuna:"טונה",dairy:"גבינות"};
const multiTypes=["veg"];
let data={
pre:{oats:[["🥣","4 כפות שיבולת שועל",5,150],["🥣","5 כפות שיבולת שועל",6,185],["🥣","6 כפות שיבולת שועל",7,220],["🥣","7 כפות שיבולת שועל",8,255]],choco:[["—","ללא שוקולית",0,0],["🍫","כפית שוקולית",0,25],["🍫","2 כפיות שוקולית",0,50]],milk:[["💧","מים",0,0],["🥛","כוס חלב 1%",7,100],["🥛","כוס חלב 3%",7,150]]},
shake:{scoop:[["—","לא בוצע",0,0],["🥤","סקופ אחד",24,120],["🥤","2 סקופים",48,240]],flavor:[["✨","רגיל",0,0],["🍫","שוקולד",0,0],["🍌","בננה",0,0]],liquid:[["💧","מים",0,0],["🥛","כוס חלב 1%",7,100],["🥛","כוס חלב 3%",7,150]]},
b:{eggs:[["—","ללא ביצים",0,0],["🥚","ביצה אחת",7,80],["🥚","2 ביצים",14,160]],tuna:[["—","ללא טונה",0,0],["🐟","חצי קופסת טונה בשמן",15,160],["🐟","קופסת טונה שלמה בשמן",30,320]],dairy:[["—","ללא גבינה",0,0],["🧀","3 כפות קוטג׳ 5%",9,100],["🧀","6 כפות קוטג׳ 5%",17,200],["🥛","6 כפות גבינה לבנה 5%",14,170]],veg:[["🥒","מלפפון",0,10],["🍅","עגבנייה",1,20],["🫑","גמבה",1,20]]},
l:{protein:[["🍗","פרוסת חזה עוף בגודל כף יד",35,210]],carb:[["🍚","2.5 אגרופי אורז",7,410],["🍚","2 אגרופי אורז",6,330],["🍚","3 אגרופי אורז",9,500]],veg:[["🥒","מלפפון",0,10],["🍅","עגבנייה",1,20],["🫑","גמבה",1,20]],sauce:[["—","ללא רוטב",0,0],["🥫","כף טריאקי",0,40],["🥫","כף ברביקיו",0,35],["🥫","כף צ׳ילי מתוק",0,50]]},
d:{protein:[["🥩","300 גרם סינטה",78,510],["🥩","300 גרם פלט איירון",78,540],["🥩","300 גרם דנבר",72,650],["🍗","300 גרם חזה עוף",93,360],["🐟","250 גרם סלמון",55,520]],carb:[["🍚","2 אגרופי אורז",6,330],["🌾","2 אגרופי כוסמת",8,330],["🍝","2 אגרופי פסטה",10,360],["🥔","תפוח אדמה גדול",7,280],["🍟","2 אגרופי צ׳יפס אייר פרייר",6,430]],veg:[["🥒","מלפפון",0,10],["🍅","עגבנייה",1,20],["🫑","גמבה",1,20]],sauce:[["—","ללא רוטב",0,0],["🥫","כף טריאקי",0,40],["🥫","כף ברביקיו",0,35],["🥫","כף צ׳ילי מתוק",0,50],["🥫","כפית מיונז",0,35]]},
s:{protein:[["🧀","קוטג׳ 250 גרם 5%",28,250],["🥛","גבינה לבנה 250 גרם 5%",25,240],["🐟","קופסת טונה בשמן",30,320],["🐟","100 גרם סלמון מעושן",22,180],["🥚","4 ביצים",28,320]],carb:[["—","ללא פחמימה",0,0],["🍞","פרוסת לחם אחת",4,90],["🥔","תפוח אדמה קטן",3,140]],veg:[["🥒","מלפפון",0,10],["🍅","עגבנייה",1,20],["🫑","גמבה",1,20]]}};
const mealTypes={pre:["oats","choco","milk"],shake:["scoop","flavor","liquid"],b:["eggs","tuna","dairy","veg"],l:["protein","carb","veg","sauce"],d:["protein","carb","veg","sauce"],s:["protein","carb","veg"]};
function qs(id){return document.getElementById(id)}function today(){return new Date().toISOString().slice(0,10)}
function toast(t){let e=qs("saveIcon");if(!e)return;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1300)}
function k(m,t){return m+"_"+t}function ss(m,t){let x=k(m,t);if(store.single[x]===undefined)store.single[x]=0;return store.single[x]}function sm(m,t){let x=k(m,t);if(!store.multi[x])store.multi[x]=[];return store.multi[x]}
function selectSingle(m,t,i){store.single[k(m,t)]=i;markMealButton(m,false);renderMealDetail();calc()}function toggleMulti(m,t,i){let a=sm(m,t);store.multi[k(m,t)]=a.includes(i)?a.filter(x=>x!==i):[...a,i];markMealButton(m,false);renderMealDetail();calc()}
function chosen(m){let out=[];(mealTypes[m]||[]).forEach(t=>{if(multiTypes.includes(t))sm(m,t).forEach(i=>data[m][t][i]&&out.push(data[m][t][i]));else out.push(data[m][t][ss(m,t)]||data[m][t][0])});return out.filter(Boolean)}
function totals(m){let it=chosen(m);return{p:it.reduce((a,x)=>a+x[2],0),c:it.reduce((a,x)=>a+x[3],0),it}}function calc(){let p=0,c=0;Object.keys(mealTypes).forEach(m=>{let t=totals(m);p+=t.p;c+=t.c});if(qs("macroBadge"))qs("macroBadge").textContent=p+" גרם";if(qs("todayProteinChip"))qs("todayProteinChip").textContent="חלבון: "+p+" גרם";if(qs("todayCalChip"))qs("todayCalChip").textContent="קלוריות: "+c;if(currentMeal&&qs("mealDetailMeta")){let t=totals(currentMeal);qs("mealDetailMeta").innerHTML=`<span class="chip ok">${t.p} גרם חלבון</span><span class="chip">${t.c} קל׳</span><span class="chip">${t.it.map(x=>x[1]).join(" + ")}</span>`}return{p,c}}
function renderMealDetail(){qs("detailTitle").textContent=mealEmoji[currentMeal]+" "+mealNames[currentMeal];let out="";mealTypes[currentMeal].forEach(t=>{let multi=multiTypes.includes(t);out+=`<div class="groupBox"><h3>${typeNames[t]}${multi?" - בחירה מרובה":""}</h3><div class="choiceGrid">`;data[currentMeal][t].forEach((it,i)=>{let sel=multi?sm(currentMeal,t).includes(i):ss(currentMeal,t)===i;out+=`<button class="choiceCard ${sel?"selected":""}" onclick="${multi?`toggleMulti('${currentMeal}','${t}',${i})`:`selectSingle('${currentMeal}','${t}',${i})`}"><div class="emoji">${it[0]}</div><b>${it[1]}</b><span>${it[2]} גרם חלבון | ${it[3]} קל׳</span></button>`});out+="</div></div>"});qs("mealDetailContent").innerHTML=out;calc()}
function hideAll(){["Dashboard","Today","MealDetail","Weight","Meals","Settings"].forEach(s=>qs("s"+s)?.classList.add("hidden"))}function openMealScreen(m){currentMeal=m;hideAll();qs("sMealDetail").classList.remove("hidden");renderMealDetail()}function backToToday(){hideAll();qs("sToday").classList.remove("hidden");renderTiles()}function saveCurrentMeal(){saveMealOnly(currentMeal);backToToday()}
function dayObj(){let d=qs("date").value||today(),old=JSON.parse(localStorage["day_"+d]||"null")||{};return{date:d,notes:qs("notes").value,store:JSON.parse(JSON.stringify(store)),mealSaved:old.mealSaved||{},macros:calc(),appVersion:APP_VERSION}}
function saveMealOnly(m){let x=dayObj();x.mealSaved[m]=true;localStorage["day_"+x.date]=JSON.stringify(x);markMealButton(m,true);toast();renderDash()}function saveDay(){let x=dayObj();x.mealSaved={pre:true,shake:true,b:true,l:true,d:true,s:true};localStorage["day_"+x.date]=JSON.stringify(x);markAllMealButtons(x.mealSaved);toast();renderDash()}
function loadDay(){let d=qs("date").value||today(),x=JSON.parse(localStorage["day_"+d]||"null");if(!x)return alert("אין רישום לתאריך");qs("notes").value=x.notes||"";if(x.store){store.single=x.store.single||{};store.multi=x.store.multi||{}}markAllMealButtons(x.mealSaved||{});calc();renderTiles();toast()}
function markMealButton(m,on){qs("tile_"+m)?.classList.toggle("saved",!!on);let t=qs("tile_"+m+"_text");if(t)t.textContent=on?"✓ נשמר":"לא נשמר"}function markAllMealButtons(s){Object.keys(mealNames).forEach(m=>markMealButton(m,s&&s[m]))}function renderTiles(){let x=JSON.parse(localStorage["day_"+(qs("date")?.value||today())]||"null");markAllMealButtons(x&&x.mealSaved?x.mealSaved:{})}
function scoreForDay(x){if(!x)return 0;let pts=0;["pre","shake","b","l","d","s"].forEach(m=>{if(x.mealSaved?.[m])pts++});return Math.round(pts/6*100)}function renderScore(){let s=scoreForDay(JSON.parse(localStorage["day_"+today()]||"null"));qs("scoreText").textContent=s+"%";qs("scoreRing").style.background=`conic-gradient(var(--green) ${s*3.6}deg,#0b101a 0deg)`;qs("scoreMeta").innerHTML=`<span class="chip ok">עמידה יומית: ${s}%</span>`}
function settings(){return JSON.parse(localStorage.settings||'{"start":96,"target":88,"startDate":""}')}function saveSettings(){localStorage.settings=JSON.stringify({start:+qs("startWeight").value,target:+qs("targetWeight").value,startDate:qs("startDate").value||today()});updateAutoWeek();renderDash();toast()}
function parseDate(s){let[a,b,c]=(s||today()).split("-").map(Number);return new Date(a,b-1,c)}function autoWeekFor(d){let st=settings(),diff=parseDate(d)-parseDate(st.startDate||today());return Math.max(1,Math.floor(diff/(7*86400000))+1)}function updateAutoWeek(){if(qs("week"))qs("week").value=autoWeekFor(qs("wdate").value||today())}
function nextFriday405(){let n=new Date(),x=new Date(n);x.setHours(4,5,0,0);let d=(5-x.getDay()+7)%7;if(d===0&&n>x)d=7;x.setDate(x.getDate()+d);return x}function enableNotifications(){if(!("Notification"in window))return alert("אין תמיכה");Notification.requestPermission().then(p=>alert(p==="granted"?"התראות הופעלו":"לא אושר"))}
function saveWeight(){updateAutoWeek();let w=+qs("weight").value;if(!w)return alert("חסר משקל");let a=JSON.parse(localStorage.weights||"[]");a.push({date:qs("wdate").value||today(),week:+qs("week").value,weight:w});localStorage.weights=JSON.stringify(a);toast();renderDash();renderWeights()}
function renderDash(){let st=settings(),a=JSON.parse(localStorage.weights||"[]").filter(x=>x.weight),w=a.length?a[a.length-1].weight:st.start;qs("heroWeight").textContent=w.toFixed(1)+" ק״ג";let lost=Math.max(0,st.start-w),left=Math.max(0,w-st.target),pct=Math.min(100,100*lost/(st.start-st.target));qs("lostKg").textContent=lost.toFixed(1);qs("leftKg").textContent=left.toFixed(1);qs("heroBar").style.width=pct+"%";qs("streak").textContent=Object.keys(localStorage).filter(k=>k.startsWith("day_")).length;qs("todayBadge").textContent=localStorage["day_"+today()]?"נשמר":"לא נשמר";drawChart(a,st);renderScore();qs("nextWeighText").textContent="התראת שקילה הבאה: "+nextFriday405().toLocaleDateString("he-IL")+" 04:05"}
function drawChart(a,st){let cv=qs("chart"),ctx=cv.getContext("2d");ctx.clearRect(0,0,cv.width,cv.height);ctx.strokeStyle="#263149";for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(35,25+i*45);ctx.lineTo(780,25+i*45);ctx.stroke()}if(a.length<2)return;let vals=a.map(x=>x.weight),min=Math.min(st.target,...vals)-1,max=Math.max(st.start,...vals)+1;ctx.strokeStyle="#43e0a8";ctx.lineWidth=5;ctx.beginPath();a.forEach((x,i)=>{let px=45+i*(700/(a.length-1)),py=260-((x.weight-min)/(max-min))*220;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke()}
function renderWeights(){let a=JSON.parse(localStorage.weights||"[]").slice().reverse();qs("weightTable").innerHTML=a.length?`<table><tr><th>תאריך</th><th>שבוע</th><th>משקל</th></tr>${a.map(x=>`<tr><td>${x.date}</td><td>${x.week||""}</td><td>${x.weight||""}</td></tr>`).join("")}</table>`:"אין שקילות"}
function renderMealBank(){let out="";Object.keys(data).forEach(m=>{out+=`<h2>${mealNames[m]}</h2>`;mealTypes[m].forEach(t=>{out+=`<table><tr><th colspan="3">${typeNames[t]}</th></tr><tr><th>רכיב</th><th>חלבון</th><th>קל׳</th></tr>`;data[m][t].forEach(i=>out+=`<tr><td>${i[0]} ${i[1]}</td><td>${i[2]}</td><td>${i[3]}</td></tr>`);out+="</table>"})});qs("mealBank").innerHTML=out}
function exportBackup(){let o={app:"DedBod",backupVersion:2,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),localStorage:{}};for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);o.localStorage[k]=localStorage.getItem(k)}let blob=new Blob([JSON.stringify(o,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="DedBod_backup_"+today()+".json";a.click()}
function importBackupFile(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let d=JSON.parse(r.result);if(!d.localStorage)return alert("קובץ לא תקין");if(confirm("לשחזר גיבוי?")){Object.keys(d.localStorage).forEach(k=>localStorage.setItem(k,d.localStorage[k]));location.reload()}};r.readAsText(f);e.target.value=""}
function show(n,b){hideAll();qs("s"+n)?.classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));if(b)b.classList.add("active");renderDash();renderWeights();renderMealBank();renderTiles();calc()}function clearAll(){if(confirm("לאפס נתונים?")){localStorage.clear();location.reload()}}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;qs("installPwaBtn").style.display="block"});async function installPwa(){if(!deferredPrompt)return alert("בכרום: תפריט ⋮ ואז התקן אפליקציה");deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;qs("installPwaBtn").style.display="none"}
function reloadApp(){if("serviceWorker"in navigator)navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.update()))).then(()=>location.reload());else location.reload()}
document.addEventListener("DOMContentLoaded",()=>{qs("date").value=today();qs("wdate").value=today();let st=settings();qs("startWeight").value=st.start;qs("targetWeight").value=st.target;qs("startDate").value=st.startDate||today();qs("wdate").addEventListener("change",updateAutoWeek);updateAutoWeek();store.single={"pre_oats":2,"pre_choco":2,"pre_milk":1,"shake_scoop":2,"shake_flavor":0,"shake_liquid":0,"b_eggs":2,"b_tuna":0,"b_dairy":2};calc();renderDash();renderWeights();renderMealBank();renderTiles();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v="+APP_VERSION).catch(()=>{})});
